### ISSUE TITLE
AttributeError in convert

### ISSUE THREAD

**Issue by lakemanr** [uhfband/keras2caffe#7]
Hello, uhfband!

I try to convert my VGG from keras to caffe and get:

Traceback (most recent call last):
  File "/media/station20/57B98E9D6C7ADB64/Eyebrows_Classification_Auqmentation_Extended_Dataset/convert_eyebrows_to_caffe.py", line 42, in <module>
    keras2caffe.convert(keras_model, 'eyebrows.prototxt', 'eyebrows.caffemodel')
  File "/media/station20/57B98E9D6C7ADB64/Eyebrows_Classification_Auqmentation_Extended_Dataset/keras2caffe/convert.py", line 244, in convert
    if type(layer.inbound_nodes[0].inbound_layers[0]).__name__ == 'Flatten':
AttributeError: 'Dense' object has no attribute 'inbound_nodes'

caffe 1.0
keras 2.2.2
tensorflow 1.7.0

Thank you!

**Comment by uhfband** [comment]
Hi!
Sorry, Keras 2.2.2 not yet supported. It should works with 2.1.2.
